python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 96}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "alpha": 0.1, "batch_size": 128, "beta": 0.1, "d_ff": 512, "d_model": 256, "horizon": 96, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 192}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "alpha": 0.1,"batch_size": 128, "beta": 0.1, "d_ff": 256, "d_model": 128, "dropout": 0.2, "e_layers": 3, "horizon": 192, "n_headers": 16, "norm": true, "num_epochs": 100, "patience": 10, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 336}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "alpha": 0.1, "batch_size": 128,"beta": 0.1, "d_ff": 256, "d_model": 128, "dropout": 0.2, "e_layers": 3, "horizon": 336, "n_headers": 16, "norm": true, "num_epochs": 100, "patience": 10, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/PatchTST"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 720}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "alpha": 0.1, "beta": 0.1, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 3, "horizon": 720, "n_headers": 16, "norm": true, "num_epochs": 100, "patience": 10, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 96}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "alpha": 0.1, "SCI": 0, "batch_size": 128, "hidden_size": 64, "horizon": 96, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 192}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "alpha": 0.1, "SCI": 0, "batch_size": 128, "hidden_size": 64, "horizon": 192, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 336}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "alpha": 0.1, "SCI": 0, "batch_size": 128, "hidden_size": 512, "horizon": 336, "lr": 0.03, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 720}' --model-name "amplifier.Amplifier" --model-hyper-params '{"alpha": 0.1, "SCI": 0, "batch_size": 32, "hidden_size": 512, "horizon": 720, "lr": 0.03, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/Amplifier"
