python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 64, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 96, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/Weather/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 64, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 192, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/Weather/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "batch_size": 64, "beta": 0.1, "d_ff": 512, "d_model": 128, "horizon": 192, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 64, "batch_size": 64, "beta": 0.1, "d_ff": 512, "d_model": 128, "horizon": 192, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "batch_size": 64, "beta": 0.1, "d_ff": 512, "d_model": 128, "horizon": 192, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "SCI": 0, "batch_size": 256, "hidden_size": 64, "horizon": 96, "label_len": 48, "lr": 0.02, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/ETTh1/Amplifier"


python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 64, "batch_size": 64, "d_ff": 512, "d_model": 128, "horizon": 336, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/ETTh1/PatchTST"


python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "batch_size": 64, "d_ff": 512, "d_model": 128, "horizon": 336, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Mix/ETTh1/PatchTST"

