python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "batch_size": 32, "beta": 0.1, "d_ff": 2048, "d_model": 512, "e_layers": 2, "factor": 3, "horizon": 96, "n_heads": 4, "norm": true, "num_epochs": 3, "seq_len": 336}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "batch_size": 64, "beta": 0.1, "d_ff": 512, "d_model": 128, "horizon": 192, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 32, "batch_size": 64, "beta": 0.1, "d_ff": 512, "d_model": 128, "horizon": 336, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"beta": 0.1, "d_ff": 256, "d_model": 128, "horizon": 720, "loss": "DBLoss", "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 64, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 96, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 64, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 192, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 64, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 336, "lr": 0.0005, "norm": true, "seq_len": 336}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "amplifier.Amplifier" --model-hyper-params '{"beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 720, "lr": 0.0005, "norm": true, "seq_len": 336}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "batch_size": 32, "beta": 0.1, "d_ff": 2048, "d_model": 512, "e_layers": 2, "factor": 3, "horizon": 96, "n_heads": 4, "norm": true, "num_epochs": 3, "seq_len": 336}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "batch_size": 64, "beta": 0.1, "d_ff": 512, "d_model": 128, "horizon": 192, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "batch_size": 64, "beta": 0.1, "d_ff": 512, "d_model": 128, "horizon": 336, "lr": 0.0001, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.03, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 96, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.05, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 192, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "amplifier.Amplifier" --model-hyper-params '{"loss": "DBLossWithShift", "lambda_shift": 0.07, "shift_k": 5, "shift_mode": "mse", "shift_tau": 1.0, "shift_window_size": 96, "beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 336, "lr": 0.0005, "norm": true, "seq_len": 336}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "amplifier.Amplifier" --model-hyper-params '{"beta": 0.3, "SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 720, "lr": 0.0005, "norm": true, "seq_len": 336}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"
